const SAMPLE_DATA = {
  categories: [
    { id: 'cat-elec', name: 'Electrónica', icon: '⚡' },
    { id: 'cat-audio', name: 'Audio', icon: '🎧' },
    { id: 'cat-peri', name: 'Periféricos', icon: '🖱️' },
    { id: 'cat-acce', name: 'Accesorios', icon: '💍' },
    { id: 'cat-cabl', name: 'Cables y Cargadores', icon: '🔌' },
  ],
  items: [
    {
      id: 'item-1',
      name: 'Laptop UltraPro X9',
      categoryId: 'cat-elec',
      rarity: 'epic',
      quantity: 1,
      price: '2499.99',
      currency: 'USD',
      acquiredFrom: 'Amazon',
      description: '64GB RAM, RTX 5090, 2TB SSD. Ilumina toda la habitación con su RGB. +50 a productividad.',
      acquiredDate: '2025-01-15',
      imageUrl: '',
    },
    {
      id: 'item-2',
      name: 'Monitor Quantum 32"',
      categoryId: 'cat-elec',
      rarity: 'rare',
      quantity: 1,
      price: '899.99',
      currency: 'CLP',
      acquiredFrom: 'MercadoLibre',
      description: '4K OLED, 240Hz. Tus ojos te lo agradecerán... o no, por las horas que pasas frente a él.',
      acquiredDate: '2025-02-10',
      imageUrl: '',
    },
    {
      id: 'item-3',
      name: 'Auriculares Astral V2',
      categoryId: 'cat-audio',
      rarity: 'legendary',
      quantity: 1,
      price: '349.99',
      currency: 'USD',
      acquiredFrom: 'Tienda Oficial',
      description: 'Cancelación de ruido activa. Te transporta a otra dimensión. Inmunidad a ruido ambiental +100%.',
      acquiredDate: '2025-03-05',
      imageUrl: '',
    },
    {
      id: 'item-4',
      name: 'Micrófono RetroWave Pro',
      categoryId: 'cat-audio',
      rarity: 'uncommon',
      quantity: 1,
      price: '79.99',
      currency: 'USD',
      acquiredFrom: 'Amazon',
      description: 'Sonido cristalino con estética retro. Tus streams sonarán como en los 80s... pero en HD.',
      acquiredDate: '2025-03-20',
      imageUrl: '',
    },
    {
      id: 'item-5',
      name: 'Ratón Phantom X Hyper',
      categoryId: 'cat-peri',
      rarity: 'legendary',
      quantity: 1,
      price: '129.99',
      currency: 'USD',
      acquiredFrom: 'MercadoLibre',
      description: '26000 DPI, 8 botones programables, peso ultraligero. +50 de puntería, +30 de velocidad.',
      acquiredDate: '2025-04-01',
      imageUrl: '',
    },
    {
      id: 'item-6',
      name: 'Teclado Mecánico Thunder',
      categoryId: 'cat-peri',
      rarity: 'epic',
      quantity: 1,
      price: '159.99',
      currency: 'USD',
      acquiredFrom: 'Amazon',
      description: 'Switches Cherry MX Blue. Tus vecinos también disfrutarán de cada tecla. Click clack CLACK.',
      acquiredDate: '2025-04-15',
      imageUrl: '',
    },
    {
      id: 'item-7',
      name: 'Alfombrilla Luminosa RGB',
      categoryId: 'cat-peri',
      rarity: 'rare',
      quantity: 1,
      price: '49.99',
      currency: 'CLP',
      acquiredFrom: 'Tienda Online',
      description: 'RGB sincronizable, superficie XXL. Porque el escritorio necesita más luces. Siempre.',
      acquiredDate: '2025-05-01',
      imageUrl: '',
    },
    {
      id: 'item-8',
      name: 'Cable USB-C Trenzado 2m',
      categoryId: 'cat-cabl',
      rarity: 'common',
      quantity: 3,
      price: '15.99',
      currency: 'CLP',
      acquiredFrom: 'Supermercado',
      description: 'Carga rápida 100W. El héroe anónimo de tu setup. Todos tenemos uno, todos lo necesitamos.',
      acquiredDate: '2025-05-10',
      imageUrl: '',
    },
    {
      id: 'item-9',
      name: 'Hub USB 7 en 1',
      categoryId: 'cat-cabl',
      rarity: 'uncommon',
      quantity: 1,
      price: '39.99',
      currency: 'CLP',
      acquiredFrom: 'MercadoLibre',
      description: 'HDMI, USB-C, SD, microSD. Conecta todo con todos. El verdadero multi-tasker.',
      acquiredDate: '2025-05-20',
      imageUrl: '',
    },
    {
      id: 'item-10',
      name: 'Soporte Ajustable Laptop',
      categoryId: 'cat-acce',
      rarity: 'common',
      quantity: 1,
      price: '29.99',
      currency: 'USD',
      acquiredFrom: 'Amazon',
      description: 'Aluminio, ajustable en altura. Tu cuello te agradecerá este item legendario nivel salud.',
      acquiredDate: '2025-06-01',
      imageUrl: '',
    },
    {
      id: 'item-11',
      name: 'Webcam 4K UltraWide',
      categoryId: 'cat-elec',
      rarity: 'epic',
      quantity: 1,
      price: '199.99',
      currency: 'USD',
      acquiredFrom: 'Tienda Oficial',
      description: '4K 60fps, auto-focus. Porque en las reuniones hay que verse bien mientras haces multitasking.',
      acquiredDate: '2025-06-15',
      imageUrl: '',
    },
    {
      id: 'item-12',
      name: 'Base Cargadora Inalámbrica',
      categoryId: 'cat-acce',
      rarity: 'rare',
      quantity: 2,
      price: '59.99',
      currency: 'CLP',
      acquiredFrom: 'Amazon',
      description: 'Carga triple: teléfono, audífonos y reloj. El trono de tus dispositivos.',
      acquiredDate: '2025-07-01',
      imageUrl: '',
    },
  ],
};
